![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [17]:
my_array = np.arange(10)
print(my_array)


[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [11]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [18]:
my_arrayimpares=my_array.copy()
impares = my_arrayimpares[my_arrayimpares % 2 != 0]

print(impares)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [20]:
array5=my_array.copy()
array5[1]=-1
array5[3]=-1
array5[5]=-1
array5[7]=-1
array5[9]=-1
print(array5)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [23]:
array6=my_array.copy()
array6[np.where(array6 % 2!= 0)] = -1
print(array6)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [27]:
array7=my_array.copy()
array7=array7.reshape(2,5)
print(array7)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [29]:
a= np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [30]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [31]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [2]:
np.concatenate?

Object `np.concatenate` not found.


1/5
(arrays: _ArrayLike[_SCT@concatenate], /, axis: SupportsIndex | None = ..., out: None = ..., *, dtype: None = ..., casting: _CastingKind | None = ...) -> NDArray[_SCT@concatenate]

concatenate(

(a1, a2, ...),
axis=0,
out=None,
dtype=None,
casting="same_kind"

)

Join a sequence of arrays along an existing axis.

Parameters
a1, a2, ... : sequence of array_like
The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

axis : int, optional
The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.

out : ndarray, optional
If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.

dtype : str or dtype
If provided, the destination array will have this dtype. Cannot be provided together with out.

versionadded

1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
Controls what kind of data casting may occur. Defaults to 'same_kind'. For a description of the options, please see casting.

versionadded

1.20.0

Returns
res : ndarray
The concatenated array.

See Also
ma.concatenate : Concatenate function that preserves input masks.

array_split : Split an array into multiple sub-arrays of equal or near-equal size.

split : Split array into a list of multiple sub-arrays of equal size.

hsplit : Split array into multiple sub-arrays horizontally (column wise).

vsplit : Split array into multiple sub-arrays vertically (row wise).

dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).

stack : Stack a sequence of arrays along a new axis.

block : Assemble arrays from blocks.

hstack : Stack arrays in sequence horizontally (column wise).

vstack : Stack arrays in sequence vertically (row wise).

dstack : Stack arrays in sequence depth wise (along third dimension).

column_stack : Stack 1-D arrays as columns into a 2-D array.

Notes
When one or more of the arrays to be concatenated is a MaskedArray, this function will return a MaskedArray object instead of an ndarray, but the input masks are not preserved. In cases where a MaskedArray is expected as input, use the ma.concatenate function from the masked array module instead.

Examples
>>> import numpy as np
>>> a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6]])
>>> np.concatenate((a, b), axis=0)
array([[1, 2],
       [3, 4],
       [5, 6]])
>>> np.concatenate((a, b.T), axis=1)
array([[1, 2, 5],
       [3, 4, 6]])
>>> np.concatenate((a, b), axis=None)
array([1, 2, 3, 4, 5, 6])
This function will not preserve masking of MaskedArray inputs.

>>> a = np.ma.arange(3)
>>> a[1] = np.ma.masked
>>> b = np.arange(2, 5)
>>> a
masked_array(data=[0, --, 2],
             mask=[False,  True, False],
       fill_value=999999)
>>> b
array([2, 3, 4])
>>> np.concatenate([a, b])
masked_array(data=[0, 1, 2, 2, 3, 4],
             mask=False,
       fill_value=999999)
>>> np.ma.concatenate([a, b])
masked_array(data=[0, --, 2, 2, 3, 4],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [43]:
array12=my_array.copy()
#1 
array12_1=array12*10
print(array12_1)
#2 
array12_1[0]
print(array12_1[0])
#3 
print(array12_1[-1])

#4 
array12[:8]

[ 0 10 20 30 40 50 60 70 80 90]
0
90


array([0, 1, 2, 3, 4, 5, 6, 7])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [45]:
my_matrix=np.random.randint(10,size=(3,3))
print(my_matrix)

[[3 6 4]
 [9 5 5]
 [2 0 2]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [50]:
ejer13=np.arange(50)
print(ejer13[1::3])


[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [57]:
ejer15=np.arange(4,1,-0.25)
print(ejer15)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [ ]:
alto largo colores rgb 

In [8]:
import numpy as np
import PIl

#img=plt.imshow("img/numpy.png")
img=PIl.Image.open('img/numpy.png')
np.array(img)

ModuleNotFoundError: No module named 'PIl'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [68]:
array17=np.random.randint(10,size=(4,1))
print(array17)
array17_2=array17.reshape(2,2)
print(array17_2)

[[2]
 [7]
 [6]
 [2]]
[[2 7]
 [6 2]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [ ]:
ejer18=np.random.randint(

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [74]:
ejer19= np.zeros((10,1),dtype=bool)
print(ejer19)
ejer19_2=ejer19.reshape(2,5)
print(ejer19_2)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [80]:
x =np.random.randint(10, 20, size = (5,2,6))
#1
print(x.size)
#2
print(x.ndim)
#3
print(x.shape)

60
3
(5, 2, 6)
