![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np
my_array=([np.arange(10)])
print(my_array)


[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [17]:

arrayalreves=np.flip(my_array)
print(arrayalreves)
array2=[arrayalreves[0,1], arrayalreves[0,2]]
print(array2)

[[9 8 7 6 5 4 3 2 1 0]]
[np.int64(8), np.int64(7)]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [23]:
array3= arrayalreves[::-1]
print(array3)

[[9 8 7 6 5 4 3 2 1 0]]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [32]:
array4=np.arange(1,21).reshape(4,5)
print(array4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [33]:
array4_invertido=array4[::-1, ::-1]
print(array4_invertido)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [34]:
array4[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [45]:
print(array4)
array4[:2,1:3]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


array([[2, 3],
       [7, 8]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [65]:
array7=array4[:,::-1]
array7_2=array7[0:3:]

print(array7_2)


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [53]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [73]:
x_loros = x[x == "Loro"]
print(x_loros)

['Loro' 'Loro']


In [74]:
for i in x:
    if i == "Loro":
        print(i)

Loro
Loro


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [107]:
ejer9=np.arange(21)
print(ejer9)
ejer9_2=ejer9[:10].reshape(2,5)
ejer9_21=ejer9[11:21].reshape(2,5)
print(ejer9_2)
print(ejer9_21)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [108]:
print(array4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [121]:
ejer10=array4[:,::-1] 

ejer10_2= ejer10[::-1]
print(ejer10_2)

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [125]:
ejer11=np.zeros(11)
print(ejer11)
print(ejer11.nbytes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
88


In [127]:
ejer11[4]=1
print(ejer11)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [132]:
ejer12=np.arange(10,50)
print(ejer12)
ejer12_invertido=ejer12[::-1]
print(ejer12_invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [146]:

ejer13=np.array([1,2,0,0,4,0])
ejer13_1=np.nonzero(ejer13)[0]
print(ejer13_1)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [151]:
ejer14=np.random.randint(20,size=(10,10))
print(ejer14)
print(ejer14.min())
print(ejer14.max())


[[14 12  8 15  3 17 12 10  6  9]
 [ 7 18 14  6  0  9 15 17  9 19]
 [10  3  9  0  4  4 11  7  6  6]
 [ 1  2 12 14 13 13 14 19  5  8]
 [17  0  2  7  1 11  6 19 19 17]
 [ 8  7  6  4 14 16  7 16  7  0]
 [14  7  8 18 13  8 16  2 13 17]
 [15 10 14 19  5  4  1 19 11  7]
 [ 5 19 13  2  7 15 10 17 17  8]
 [ 6  5 12 13 18  7 16 10 15  4]]
0
19


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [161]:
ejer15=np.empty(30)
print(ejer15.mean())


0.40665146041808076


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [201]:
x=np.zeros(25,dtype=int)

x2=x.reshape(5,5)

x2[0,:]=1
x2[:,-1]=1
x2[:,0]=1
x2[-1,:]=1
print (x2)




[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```


In [19]:
ejer17=np.array([0,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0])
x=ejer17.reshape(4,4)
y=ejer17.reshape(4,4)
np.vstack([x,y])
z=ejer17.reshape(4,4)
b=ejer17.reshape(4,4)
matriz=np.hstack([x,y])
matriz2=np.hstack([z,b])
matriz[1]=matriz[2]
matriz[2]=matriz[0]
matriz2[1]=matriz2[2]
matriz2[2]=matriz2[0]
#print(matriz)
#print(matriz2)
unidas=np.vstack([matriz,matriz2])
print(unidas)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [46]:
ejer18=np.array([[0,1],
                [1,0]])

np.tile(ejer18,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [57]:
ejer19= np.random.rand(5, 5)
media=np.mean(ejer19)
print(media)
desviacion=np.std(ejer19)
print(desviacion)
normalizada=np.subtract(ejer19,media)/desviacion
print(normalizada)


0.4546852083275557
0.2470468624273128
[[-0.97552561  0.21312775  0.57802861  0.60955445  1.79793003]
 [-0.21798667 -1.24265048 -1.50175687  0.29030795  1.74326126]
 [ 0.03288434 -1.43765374  0.56802083 -1.14097706  0.89219794]
 [ 0.30751096  0.11734095  1.58166055  1.2589249  -0.53580711]
 [ 0.02087021 -1.73714545 -0.54691226 -0.87562189  0.2004164 ]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [70]:
ejer20=np.array([6,3,4,5,2,7,8,10,1,9])

ejer20_1=np.where((ejer20 >= 3) & (ejer20 <= 8), -1, ejer20)
print(ejer20_1)

[-1 -1 -1 -1  2 -1 -1 10  1  9]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.